app:
  name: "onereseve"

server:
  host: "localhost"
  port: "3000"

db:
  username: "root"
  password: ""
  host: "127.0.0.1"
  port: "3306"
  name: "resedist"

dblog:
  LogLevel: 4
  Colorful: true

jwt:
    secret: "sdfsdfsdfsdfsdfs"