app:
  name: "onereseve"

server:
  host: "localhost"
  port: "3000"

db:
  username: "root"
  password: ""
  host: "192.168.100.127"
  port: "3306"
  name: "resedist"

dblog:
  LogLevel: 4
  Colorful: true