app:
  name: "onereseve"

server:
  host: "localhost"
  port: "8080"

db:
  username: "root"
  password: ""
  host: "127.0.0.1"
  port: "3306"
  name: "resedist"

dblog:
  LogLevel: 4
  Colorful: true

jwt:
    secret: "fc2e19d78c179b5dbb5358069f73156f835030ee43afe0fa9e257cdb421ccc5c"
    duration: "0h30m0s"

cors:
  AllowOrigins:
    - "http://localhost:3000"
    - "http://localhost:80"

  AllowMethods: ["GET", "POST", "PUT", "DELETE"]
  AllowHeaders: ["Origin", "Content-Type", "Authorization"]
  ExposeHeaders: ["Content-Length"]
  AllowCredentials: true


